server:
  port: 8080

spring:
  application:
    name: Inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/springbatch16
    username: root
    password: Hemanth@#123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
